data:
  ts_len: 100
  test_ratio: 0.5
  batch_size: 128
  num_workers: 0
  rand_seed: 0
  augmentations:
    -

enc_param:
  name: 'resnet18'
  out_size_enc: 512
  proj_hid: 2048
  proj_out: 2048

clf_param:
  in_size: 512
  out_size: 2

vibcreg:
  lambda_: 25
  mu: 25
  nu: 10

loss_weight:
  use_class_weight: True
  label_smoothing: 0.
  w_clf: 1.
  w_vibcreg: 0.1


exp_params:
  LR : 0.001 #0.0001
  weight_decay: 0.00001
  gradient_clip_val: 0.5
  model_save_ep_period: 50

trainer_params:
  gpus:
    - 0
  max_epochs: 200 #50
