data:
#  train_data_ratio: 0.8  # make it inherent
#  test_data_ratio: 0.2  # make it inherent
#  train_test_split_rand_seed: 0  # make it inherent
  batch_size: 256
  num_workers: 0
  augmentations:
    # -

enc_param:
  name: 'resnet18'
  in_channels: 1
#  last_channels_enc: 512
#  proj_hid: 4096
#  proj_out: 4096
#  backbone_type: 'ResNet34Encoder' #'ResNet18Encoder', 'ViTEncoder'
#  use_encoder: True
#  use_encoder_ts: False

clf_param:
  in_size: 512
  out_size: 2  # n_classes

exp_params:
  # loss function tuning parameters
  LR : 0.001
  weight_decay: 0.00001
  model_save_ep_period: 50

trainer_params:
  gpus:
    - 0
  max_epochs: 300
