data:
  ts_len: 300
  test_ratio: 0.3
  batch_size: 64 #32
  num_workers: 0
  rand_seed: 0
  augmentations:
    -

enc_param:
  name: 'simplenet'

vibcreg:
  lambda_: 25
  mu: 25
  nu: 10

loss_weight:
  use_class_weight: True
  w_vibcreg: 0 #0.1
  w_clf: 0.1

clf_param:
  in_size: 64
  out_size: 1  # binary clf

exp_params:
  LR : 0.0001
  weight_decay: 0. # 0.00001
  gradient_clip_val: 0.5
  model_save_ep_period: 50

trainer_params:
  gpus:
    - 0
  max_epochs: 300
